from __future__ import annotations

import json
from pathlib import Path

from create_ai_app.models import ProjectConfig


def install(cfg: ProjectConfig, target: Path) -> None:
    if cfg.frontend == "Next.js 15":
        _write_nextjs(cfg, target)
    elif cfg.frontend == "Streamlit":
        _write_streamlit(cfg, target)
    elif cfg.frontend == "Chainlit":
        _write_chainlit(cfg, target)


def _write_nextjs(cfg: ProjectConfig, target: Path) -> None:
    frontend = target / "frontend"
    frontend.mkdir(exist_ok=True)

    # Build package.json deps based on choices
    deps: dict = {
        "next": "^15.0.0",
        "react": "^18.0.0",
        "react-dom": "^18.0.0",
    }
    dev_deps: dict = {
        "typescript": "^5.0.0",
        "@types/node": "^22.0.0",
        "@types/react": "^18.0.0",
        "@types/react-dom": "^18.0.0",
    }

    if cfg.frontend_tailwind:
        dev_deps.update({
            "tailwindcss": "^3.4.0",
            "postcss": "^8.4.0",
            "autoprefixer": "^10.4.0",
        })

    if cfg.frontend_shadcn:
        deps.update({
            "class-variance-authority": "^0.7.0",
            "clsx": "^2.1.0",
            "tailwind-merge": "^2.3.0",
            "lucide-react": "^0.400.0",
        })

    (frontend / "package.json").write_text(json.dumps({
        "name": f"{cfg.name}-frontend",
        "version": "0.1.0",
        "private": True,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "lint": "next lint",
        },
        "dependencies": deps,
        "devDependencies": dev_deps,
    }, indent=2) + "\n")

    (frontend / "tsconfig.json").write_text(json.dumps({
        "compilerOptions": {
            "target": "ES2017",
            "lib": ["dom", "dom.iterable", "esnext"],
            "allowJs": True,
            "skipLibCheck": True,
            "strict": True,
            "noEmit": True,
            "esModuleInterop": True,
            "module": "esnext",
            "moduleResolution": "bundler",
            "resolveJsonModule": True,
            "isolatedModules": True,
            "jsx": "preserve",
            "incremental": True,
            "plugins": [{"name": "next"}],
            "paths": {"@/*": ["./src/*"]},
        },
        "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        "exclude": ["node_modules"],
    }, indent=2) + "\n")

    (frontend / "next.config.ts").write_text("""import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
""")

    (frontend / ".env.local.example").write_text(
        "NEXT_PUBLIC_API_URL=http://localhost:3100\n"
    )

    # app/ directory
    app_dir = frontend / "src" / "app"
    app_dir.mkdir(parents=True, exist_ok=True)

    if cfg.frontend_tailwind:
        (frontend / "tailwind.config.ts").write_text("""import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
""")
        (frontend / "postcss.config.mjs").write_text("""const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
""")
        globals_css = "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n"
    else:
        globals_css = "* { box-sizing: border-box; }\nbody { margin: 0; font-family: sans-serif; }\n"

    (app_dir / "globals.css").write_text(globals_css)

    # layout.tsx
    (app_dir / "layout.tsx").write_text(f"""import type {{ Metadata }} from "next";
import "./globals.css";

export const metadata: Metadata = {{
  title: "{cfg.name}",
  description: "Generated by create-ai-app",
}};

export default function RootLayout({{
  children,
}}: {{
  children: React.ReactNode;
}}) {{
  return (
    <html lang="en">
      <body>{{children}}</body>
    </html>
  );
}}
""")

    # page.tsx — shadcn version or plain
    if cfg.frontend_shadcn:
        page_content = _shadcn_page(cfg)
        # Write shadcn component stubs
        ui_dir = frontend / "src" / "components" / "ui"
        ui_dir.mkdir(parents=True, exist_ok=True)
        _write_shadcn_button(ui_dir)
        _write_shadcn_card(ui_dir)
        _write_shadcn_utils(frontend / "src" / "lib")
    else:
        page_content = _plain_page(cfg)

    (app_dir / "page.tsx").write_text(page_content)


def _shadcn_page(cfg: ProjectConfig) -> str:
    return f'''"use client";

import {{ useState }} from "react";
import {{ Button }} from "@/components/ui/button";
import {{ Card, CardContent, CardHeader, CardTitle }} from "@/components/ui/card";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3100";

export default function Home() {{
  const [input, setInput] = useState("");
  const [output, setOutput] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {{
    e.preventDefault();
    setLoading(true);
    try {{
      const res = await fetch(`${{API_URL}}/api/process`, {{
        method: "POST",
        headers: {{ "Content-Type": "application/json" }},
        body: JSON.stringify({{ input }}),
      }});
      const data = await res.json();
      setOutput(data.output);
    }} catch (err) {{
      setOutput("Error: " + String(err));
    }} finally {{
      setLoading(false);
    }}
  }};

  return (
    <main className="min-h-screen bg-background flex items-center justify-center p-8">
      <Card className="w-full max-w-2xl">
        <CardHeader>
          <CardTitle>{cfg.name}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <form onSubmit={{handleSubmit}} className="space-y-4">
            <textarea
              className="w-full min-h-[120px] p-3 border rounded-md resize-none focus:outline-none focus:ring-2 focus:ring-ring"
              value={{input}}
              onChange={{(e) => setInput(e.target.value)}}
              placeholder="Enter your input..."
            />
            <Button type="submit" disabled={{loading}} className="w-full">
              {{loading ? "Processing..." : "Submit"}}
            </Button>
          </form>
          {{output && (
            <pre className="p-4 bg-muted rounded-md text-sm whitespace-pre-wrap">
              {{output}}
            </pre>
          )}}
        </CardContent>
      </Card>
    </main>
  );
}}
'''


def _plain_page(cfg: ProjectConfig) -> str:
    return f'''"use client";

import {{ useState }} from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3100";

export default function Home() {{
  const [input, setInput] = useState("");
  const [output, setOutput] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {{
    e.preventDefault();
    setLoading(true);
    try {{
      const res = await fetch(`${{API_URL}}/api/process`, {{
        method: "POST",
        headers: {{ "Content-Type": "application/json" }},
        body: JSON.stringify({{ input }}),
      }});
      const data = await res.json();
      setOutput(data.output);
    }} catch (err) {{
      setOutput("Error: " + String(err));
    }} finally {{
      setLoading(false);
    }}
  }};

  return (
    <main style={{{{ padding: "2rem", maxWidth: "800px", margin: "0 auto" }}}}>
      <h1>{cfg.name}</h1>
      <form onSubmit={{handleSubmit}}>
        <textarea
          value={{input}}
          onChange={{(e) => setInput(e.target.value)}}
          rows={{4}}
          style={{{{ width: "100%", marginBottom: "1rem" }}}}
          placeholder="Enter your input..."
        />
        <br />
        <button type="submit" disabled={{loading}}>
          {{loading ? "Processing..." : "Submit"}}
        </button>
      </form>
      {{output && <pre style={{{{ marginTop: "1rem", whiteSpace: "pre-wrap" }}}}>{{output}}</pre>}}
    </main>
  );
}}
'''


def _write_shadcn_button(ui_dir: Path) -> None:
    (ui_dir / "button.tsx").write_text('''import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const buttonVariants = cva(
  "inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        ghost: "hover:bg-accent hover:text-accent-foreground",
      },
      size: {
        default: "h-10 px-4 py-2",
        sm: "h-9 rounded-md px-3",
        lg: "h-11 rounded-md px-8",
      },
    },
    defaultVariants: { variant: "default", size: "default" },
  }
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => (
    <button className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />
  )
);
Button.displayName = "Button";

export { Button, buttonVariants };
''')


def _write_shadcn_card(ui_dir: Path) -> None:
    (ui_dir / "card.tsx").write_text('''import * as React from "react";
import { cn } from "@/lib/utils";

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("rounded-lg border bg-card text-card-foreground shadow-sm", className)} {...props} />
  )
);
Card.displayName = "Card";

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />
  )
);
CardHeader.displayName = "CardHeader";

const CardTitle = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h3 ref={ref} className={cn("text-2xl font-semibold leading-none tracking-tight", className)} {...props} />
  )
);
CardTitle.displayName = "CardTitle";

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
  )
);
CardContent.displayName = "CardContent";

export { Card, CardHeader, CardTitle, CardContent };
''')


def _write_shadcn_utils(lib_dir: Path) -> None:
    lib_dir.mkdir(parents=True, exist_ok=True)
    (lib_dir / "utils.ts").write_text('''import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
''')


def _write_streamlit(cfg: ProjectConfig, target: Path) -> None:
    (target / "app.py").write_text(f"""import streamlit as st
import requests
import os

API_URL = os.getenv("API_URL", "http://localhost:3100")

st.title("{cfg.name}")

if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

if prompt := st.chat_input("Enter your message..."):
    st.session_state.messages.append({{"role": "user", "content": prompt}})
    with st.chat_message("user"):
        st.write(prompt)
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                response = requests.post(
                    f"{{API_URL}}/api/process",
                    json={{"input": prompt}},
                    timeout=60,
                )
                response.raise_for_status()
                output = response.json().get("output", "")
            except Exception as e:
                output = f"Error: {{e}}"
        st.write(output)
    st.session_state.messages.append({{"role": "assistant", "content": output}})
""")


def _write_chainlit(cfg: ProjectConfig, target: Path) -> None:
    (target / "app.py").write_text(f"""import chainlit as cl
import requests
import os

API_URL = os.getenv("API_URL", "http://localhost:3100")


@cl.on_chat_start
async def on_chat_start():
    await cl.Message(content="Hello! How can I help you?").send()


@cl.on_message
async def on_message(message: cl.Message):
    try:
        response = requests.post(
            f"{{API_URL}}/api/process",
            json={{"input": message.content}},
            timeout=60,
        )
        response.raise_for_status()
        output = response.json().get("output", "")
    except Exception as e:
        output = f"Error: {{e}}"
    await cl.Message(content=output).send()
""")
